#!/usr/bin/env python3
"""Generate or check the radio's bitmap fonts from VT323.

  build_fonts.py            rewrite app/services/gfx/font_vt323.{c,h}
  build_fonts.py --check    exit 1 if either is out of date

VT323 (VT323-Regular.ttf here, SIL Open Font License 1.1, see OFL.txt) is
drawn on a pixel grid of 40 font units, so it is crisp at 25 px per em and
its multiples. The screens use it at 25 px and, for small text, at 17 px;
large digits are the 25 px glyphs drawn at scale 2 (services/gfx), which
keeps them crisp and costs no flash.

Glyphs are FreeType's monochrome rendering through Pillow, so the pinned
Pillow version in tools/requirements.txt (which bundles FreeType) decides
the exact bits. Printable ASCII only.
"""

import argparse
import sys
from pathlib import Path

from PIL import ImageFont

ROOT = Path(__file__).resolve().parent.parent.parent
TTF = Path(__file__).resolve().parent / "VT323-Regular.ttf"
OUT_C = ROOT / "app" / "services" / "gfx" / "font_vt323.c"
OUT_H = ROOT / "app" / "services" / "gfx" / "font_vt323.h"
SIZES = (17, 25)
FIRST, LAST = 0x20, 0x7E


def rasterise(size):
    """Glyphs at size px per em: (metrics, [(char, glyph dict, bits)])."""
    font = ImageFont.truetype(str(TTF), size)
    ascent, descent = font.getmetrics()
    cap_top = font.getbbox("H", anchor="ls")[1]
    glyphs = []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        mask, (ox, oy) = font.getmask2(ch, mode="1", anchor="la")
        w, h = mask.size
        bits = [1 if mask.getpixel((x, y)) else 0 for y in range(h) for x in range(w)]
        if not any(bits):
            w, h, ox, oy, bits = 0, 0, 0, 0, []
        advance = round(font.getlength(ch))
        glyphs.append((ch, {"width": w, "height": h, "x": ox, "y": oy, "advance": advance}, bits))
    return {"line_height": ascent + descent, "ascent": ascent, "cap_height": -cap_top}, glyphs


def pack(bits):
    out = []
    for i in range(0, len(bits), 8):
        byte = 0
        for j, b in enumerate(bits[i:i + 8]):
            byte |= b << (7 - j)
        out.append(byte)
    return out


def c_char(ch):
    return {"\\": "'\\\\'", "'": "'\\''"}.get(ch, f"'{ch}'")


def generate():
    header = [
        "/*",
        " * VT323 bitmap fonts. Generated by tools/fonts/build_fonts.py; do not edit.",
        " * VT323: Copyright 2011, The VT323 Project Authors (peter.hull@oikoi.com),",
        " * SIL Open Font License 1.1 (tools/fonts/OFL.txt).",
        " */",
    ]
    h = header + ["", "#ifndef SERVICES_GFX_FONT_VT323_H_", "#define SERVICES_GFX_FONT_VT323_H_", "",
                  '#include "services/gfx/gfx.h"', ""]
    c = header + ["", '#include "services/gfx/font_vt323.h"', ""]
    for size in SIZES:
        metrics, glyphs = rasterise(size)
        name = f"gfx_vt323_{size}"
        h.append(f"/** VT323 at {size} px: line {metrics['line_height']} px, "
                 f"cap height {metrics['cap_height']} px. */")
        h.append(f"extern const struct gfx_font {name};")
        data, entries, offset = [], [], 0
        for ch, g, bits in glyphs:
            packed = pack(bits)
            entries.append(f"\t{{{offset}, {g['width']}, {g['height']}, {g['x']}, {g['y']}, "
                           f"{g['advance']}}}, /* {c_char(ch)} */")
            data.extend(packed)
            offset += len(packed)
        if offset > 0xFFFF:
            sys.exit(f"{name}: bitmap data exceeds a 16-bit offset")
        c.append(f"static const uint8_t {name}_bitmaps[{len(data)}] = {{")
        for i in range(0, len(data), 16):
            c.append("\t" + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]) + ",")
        c.append("};")
        c.append("")
        c.append(f"static const struct gfx_glyph {name}_glyphs[{len(glyphs)}] = {{")
        c.append("\t/* offset, width, height, x, y, advance */")
        c.extend(entries)
        c.append("};")
        c.append("")
        c.append(f"const struct gfx_font {name} = {{")
        c.append(f"\t.line_height = {metrics['line_height']},")
        c.append(f"\t.ascent = {metrics['ascent']},")
        c.append(f"\t.cap_height = {metrics['cap_height']},")
        c.append(f"\t.first = {c_char(chr(FIRST))},")
        c.append(f"\t.last = {c_char(chr(LAST))},")
        c.append(f"\t.glyphs = {name}_glyphs,")
        c.append(f"\t.bitmaps = {name}_bitmaps,")
        c.append("};")
        c.append("")
    h += ["", "#endif /* SERVICES_GFX_FONT_VT323_H_ */"]
    return "\n".join(c), "\n".join(h) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="fail if the generated files are stale")
    args = ap.parse_args()
    outputs = dict(zip((OUT_C, OUT_H), generate()))
    if args.check:
        stale = [p for p, text in outputs.items() if not p.exists() or p.read_text() != text]
        for p in stale:
            print(f"{p.relative_to(ROOT)} is out of date: run tools/fonts/build_fonts.py", file=sys.stderr)
        return 1 if stale else 0
    for p, text in outputs.items():
        p.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
