/*
 * VT323 bitmap fonts. Generated by tools/fonts/build_fonts.py; do not edit.
 * VT323: Copyright 2011, The VT323 Project Authors (peter.hull@oikoi.com),
 * SIL Open Font License 1.1 (tools/fonts/OFL.txt).
 */

#ifndef SERVICES_GFX_FONT_VT323_H_
#define SERVICES_GFX_FONT_VT323_H_

#include "services/gfx/gfx.h"

/** VT323 at 17 px: line 18 px, cap height 10 px. */
extern const struct gfx_font gfx_vt323_17;
/** VT323 at 25 px: line 25 px, cap height 14 px. */
extern const struct gfx_font gfx_vt323_25;

#endif /* SERVICES_GFX_FONT_VT323_H_ */
