#!/usr/bin/env python3
"""Build the iPhone app's county table from the U.S. Census Bureau FIPS lists.

  build_counties.py                 download the Census files and write the table
  build_counties.py --from DIR      use national_county2020.txt and
                                    national_state2020.txt already in DIR

Writes swift/SamewiseKit/Sources/SamewiseKit/Resources/counties.txt: comment
lines naming the source and date, then one line per state
(`SS|000||ST|State name`) and per county or equivalent, territories included
(`SS|CCC|County name|ST|State name`). The SAME location code for a whole
county is 0 + SS + CCC.
"""

import argparse
import csv
import datetime
import io
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
OUT = ROOT / "swift" / "SamewiseKit" / "Sources" / "SamewiseKit" / "Resources" / "counties.txt"
BASE = "https://www2.census.gov/geo/docs/reference/codes2020/"
COUNTY_FILE = "national_county2020.txt"
STATE_FILE = "national_state2020.txt"


def read_rows(text: str) -> list[dict]:
    """Pipe-delimited with a header line, as the Census publishes them."""
    return list(csv.DictReader(io.StringIO(text.lstrip("\ufeff")), delimiter="|"))


def fetch(name: str, source_dir: Path | None) -> str:
    if source_dir is not None:
        return (source_dir / name).read_text(encoding="utf-8-sig")
    with urllib.request.urlopen(BASE + name, timeout=60) as r:
        return r.read().decode("utf-8-sig")


def build(county_text: str, state_text: str, date: str) -> str:
    states = {}
    for r in read_rows(state_text):
        states[r["STATEFP"]] = (r["STATE"], r["STATE_NAME"])
    lines = [
        "# U.S. counties and equivalents for SAME location codes (0 + state FIPS + county FIPS).",
        f"# Source: U.S. Census Bureau, 2020 FIPS codes, {BASE}{COUNTY_FILE} and {STATE_FILE}, retrieved {date}",
        "# Generated by tools/counties/build_counties.py; don't edit.",
        "# state FIPS|county FIPS (000 = the state)|county name|state postal code|state name",
    ]
    rows = []
    for fips, (postal, name) in states.items():
        rows.append((fips, "000", "", postal, name))
    for r in read_rows(county_text):
        fips = r["STATEFP"]
        postal, name = states.get(fips, (r["STATE"], r["STATE"]))
        rows.append((fips, r["COUNTYFP"], r["COUNTYNAME"].strip(), postal, name))
    for row in sorted(set(rows)):
        if any("|" in field for field in row):
            raise ValueError(f"unexpected '|' in {row}")
        lines.append("|".join(row))
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--from", dest="source", type=Path, help="directory holding the two Census files")
    p.add_argument("--date", default=datetime.date.today().isoformat(), help="retrieval date for the header")
    p.add_argument("--out", type=Path, default=OUT)
    a = p.parse_args(argv)
    text = build(fetch(COUNTY_FILE, a.source), fetch(STATE_FILE, a.source), a.date)
    a.out.write_text(text, encoding="utf-8")
    print(f"wrote {a.out} ({text.count(chr(10)) - 4} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
