#!/usr/bin/env python3
"""The XIAO bench report (milestone 3.5) from a Renode run.

Inputs: the emulated console (tests/renode, UART0 to a file), the
executed-instruction counter at the benchmark's start and end markers, the
lines the clip should decode to (tools/vectors/build_clip.py), the size
report (tools/size) and, optionally, the same app's console on native_sim.

Checks, each failing the run:
  - the clip decodes on the emulated chip to the expected header and EOM,
    and to exactly what native_sim decoded;
  - estimated CPU load at 1.5 cycles per instruction is at most 10% of the
    64 MHz core;
  - every thread's stack high-water mark is at most 75% of its size;
  - the image is within the size budget.

Writes Markdown (docs/xiao-bench.md) and JSON.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

SAMPLE_RATE = 16_000_000 / 1536
CPU_HZ = 64_000_000
CPIS = (1.0, 1.25, 1.5)
CPU_LIMIT_PCT = 10.0
CPI_FOR_LIMIT = 1.5
STACK_LIMIT_PCT = 75.0

_STACK = re.compile(r"^\s*(?P<name>.*?)\s*: STACK: unused (?P<unused>\d+) usage (?P<used>\d+) / (?P<size>\d+)")
_END = re.compile(r"WX BENCH END samples=(?P<samples>\d+)")


def console_lines(text: str) -> list[str]:
    return [line.rstrip("\r") for line in text.replace("\r\n", "\n").split("\n")]


def decoded(lines: list[str]) -> list[str]:
    """The decoder's events, in order."""
    return [line.strip() for line in lines if line.strip().startswith(("WX HEADER ", "WX EOM"))]


def samples(lines: list[str]) -> int:
    for line in lines:
        m = _END.search(line)
        if m:
            return int(m.group("samples"))
    raise ValueError("no 'WX BENCH END samples=' line on the console")


def stacks(lines: list[str]) -> list[dict]:
    out = []
    for line in lines:
        m = _STACK.match(line)
        if m:
            used, size = int(m.group("used")), int(m.group("size"))
            out.append({"thread": m.group("name") or "?", "used": used, "size": size,
                        "pct": round(used * 100 / size, 1)})
    return out


def cpu(instructions: int, n_samples: int) -> dict:
    seconds = n_samples / SAMPLE_RATE
    ips = instructions / seconds
    return {"instructions": instructions, "audio_seconds": round(seconds, 3),
            "instructions_per_audio_second": round(ips),
            "load_pct": {str(c): round(ips * c * 100 / CPU_HZ, 2) for c in CPIS}}


def read_counts(path: Path) -> int:
    kv = dict(line.split("=", 1) for line in path.read_text().split() if "=" in line)
    return int(kv["end"]) - int(kv["start"])


def evaluate(uart: str, counts: int, expected: list[str], native: list[str] | None, size: dict | None) -> dict:
    lines = console_lines(uart)
    got = decoded(lines)
    c = cpu(counts, samples(lines))
    st = stacks(lines)
    checks = {
        "decodes_expected": got == expected,
        "matches_native_sim": native is None or got == decoded(native),
        "cpu_within_limit": c["load_pct"][str(CPI_FOR_LIMIT)] <= CPU_LIMIT_PCT,
        "stacks_within_limit": bool(st) and all(s["pct"] <= STACK_LIMIT_PCT for s in st),
        "size_within_budget": size is None or bool(size.get("ok")),
    }
    return {"decoded": got, "expected": expected, "native_checked": native is not None,
            "cpu": c, "stacks": st, "size": size, "checks": checks, "ok": all(checks.values())}


def _kb(n: int) -> str:
    return f"{n / 1024:.1f} KB"


def markdown(r: dict) -> str:
    c = r["cpu"]
    tick = {True: "pass", False: "**FAIL**"}
    out = [
        "# XIAO bench (milestone 3.5)", "",
        "Generated by `tests/renode/run.sh` (`tools/renode/bench.py`) from the `xiao_ble/nrf52840` image "
        "running on Renode's emulated nRF52840. Emulation gives instruction counts, not cycles, and "
        "models no flash wait states, caches or real peripherals: milestone 4 measures on the board.", "",
        "| Check | Result |", "| --- | --- |",
    ]
    names = {
        "decodes_expected": "The embedded clip decodes to the expected header and EOM",
        "matches_native_sim": "Same header and EOM as on native_sim",
        "cpu_within_limit": f"CPU load at {CPI_FOR_LIMIT} cycles per instruction at most {CPU_LIMIT_PCT:g}%",
        "stacks_within_limit": f"Every thread's stack high-water mark at most {STACK_LIMIT_PCT:g}%",
        "size_within_budget": "Image within the size budget",
    }
    for k, v in r["checks"].items():
        note = "" if k != "matches_native_sim" or r["native_checked"] else " (not compared in this run)"
        out.append(f"| {names[k]} | {tick[v]}{note} |")
    if r["size"]:
        s = r["size"]
        out += ["", "## Size", "",
                "| | Used | Budget |", "| --- | --- | --- |",
                f"| Flash | {_kb(s['flash'])} ({s['flash'] * 100 / s['slot']:.1f}% of a {_kb(s['slot'])} slot) "
                f"| {_kb(s['flash_budget'])} (75%) |",
                f"| RAM | {_kb(s['ram'])} ({s['ram'] * 100 / s['ram_size']:.1f}% of 256 KB) "
                f"| {_kb(s['ram_budget'])} (70%) |",
                "",
                f"The flash slot assumes MCUboot with two slots: 1 MB = 48 KB MCUboot + 2 x {_kb(s['slot'])} "
                f"+ 32 KB settings storage. The embedded SAME clip is {_kb(s['clip'])} of the image."]
    out += ["", "## Decoding", "",
            f"The clip ({c['audio_seconds']} s of audio) decoded on the emulated chip to:", ""]
    out += [f"- `{line}`" for line in r["decoded"]]
    out += ["", "## CPU estimate", "",
            f"{c['instructions']:,} instructions between the markers for {c['audio_seconds']} s of audio: "
            f"{c['instructions_per_audio_second']:,} instructions per second of audio. On the 64 MHz Cortex-M4F:", "",
            "| Cycles per instruction | CPU load |", "| --- | --- |"]
    out += [f"| {cpi} | {pct}% |" for cpi, pct in c["load_pct"].items()]
    out += ["", "The count covers everything that ran between the markers: decoding, the alert "
            "manager handling the header and EOM, and the console lines.",
            "", "## Stacks", "",
            "Thread analyzer high-water marks after the benchmark and Bluetooth start-up:", "",
            "| Thread | Used | Size | Share |", "| --- | --- | --- | --- |"]
    out += [f"| {s['thread']} | {s['used']} B | {s['size']} B | {s['pct']}% |"
            for s in sorted(r["stacks"], key=lambda s: -s["pct"])]
    out += ["", "## Known limits of the emulation", "",
            "- Bluetooth does not start in Renode: the SoftDevice Controller's `sdc_enable` fails (-33) "
            "because Renode's PPI model can't take the channels it needs. The firmware reports it and "
            "decodes regardless; Bluetooth is tested on `nrf52_bsim` instead.",
            "- Renode models neither the CryptoCell nor the QSPI flash, so the image uses software crypto "
            "and the RNG peripheral, and leaves the QSPI flash off.", ""]
    return "\n".join(out)


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--uart", type=Path, required=True)
    p.add_argument("--instructions", type=Path, required=True)
    p.add_argument("--expected", type=Path, required=True, help="wx_clip.txt from the build")
    p.add_argument("--native", type=Path, help="native_sim console of the same app")
    p.add_argument("--size", type=Path, help="tools/size JSON")
    p.add_argument("--markdown", type=Path, required=True)
    p.add_argument("--json", type=Path)
    a = p.parse_args(argv)
    expected = [line for line in a.expected.read_text().split("\n") if line]
    native = console_lines(a.native.read_text()) if a.native else None
    size = json.loads(a.size.read_text()) if a.size and a.size.exists() else None
    r = evaluate(a.uart.read_text(errors="replace"), read_counts(a.instructions), expected, native, size)
    a.markdown.write_text(markdown(r))
    if a.json:
        a.json.write_text(json.dumps(r, indent=2) + "\n")
    print(markdown(r))
    for k, v in r["checks"].items():
        if not v:
            print(f"FAILED: {k}", file=sys.stderr)
    return 0 if r["ok"] else 1


if __name__ == "__main__":
    sys.exit(main())
