#!/usr/bin/env python3
"""Build the SAME clip compiled into firmware images without a host file
system (the XIAO and its Renode run): one header, three copies, then EOM.

Writes, into --out:
  wx_clip.c      the samples as a C array in flash (int8 or int16)
  wx_clip.h      its declarations
  wx_clip.json   the samegen sidecar, with the expected header and EOM count
  wx_clip.txt    the lines a correct decoder prints for it (see app/src/main.c)

The firmware expands int8 samples to int16 by shifting left 8 bits. Like
every vector, the clip is generated, never edited.

  build_clip.py --out build/clip [--bits 8|16]
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path

import numpy as np

_here = Path(__file__).resolve().parent
_spec = importlib.util.spec_from_file_location("samegen_module", _here.parent / "samegen" / "samegen.py")
sg = importlib.util.module_from_spec(_spec)
sys.modules[_spec.name] = sg
_spec.loader.exec_module(sg)

HEADER = "ZCZC-WXR-TOR-048453+0030-2781915-KEWX/NWS-"
OPTIONS = sg.Options(lead_s=0.25, trail_s=0.25, message_gap_s=0.5)


def expected_lines(sidecar: dict) -> list[str]:
    """What app/src/main.c prints for the clip, in order."""
    lines = [f"WX HEADER {h}" for h in sidecar["expected_headers"]]
    lines += ["WX EOM"] * sidecar["expected_eom_count"]
    return lines


def build(out: Path, bits: int = 16) -> dict:
    samples, sidecar = sg.generate([HEADER, "EOM"], OPTIONS)
    out.mkdir(parents=True, exist_ok=True)
    if bits == 8:
        data = (samples.astype(np.int32) >> 8).astype(np.int8)
        ctype, shift = "int8_t", 8
    elif bits == 16:
        data, ctype, shift = samples, "int16_t", 0
    else:
        raise ValueError("bits must be 8 or 16")
    sidecar["clip_bits"] = bits

    (out / "wx_clip.h").write_text(
        "/* Generated by tools/vectors/build_clip.py. Do not edit. */\n"
        "#ifndef WX_CLIP_H_\n#define WX_CLIP_H_\n\n#include <stdint.h>\n\n"
        f"#define WX_CLIP_SHIFT {shift}\n"
        f"extern const {ctype} wx_clip_samples[];\n"
        "extern const uint32_t wx_clip_count;\n\n#endif\n")
    rows = []
    for i in range(0, len(data), 16):
        rows.append("\t" + ", ".join(str(int(x)) for x in data[i:i + 16]) + ",")
    (out / "wx_clip.c").write_text(
        "/* Generated by tools/vectors/build_clip.py from tools/samegen. Do not edit. */\n"
        f'/* {HEADER} x3, then EOM x3; {len(data)} samples at {sg.SAME_RATE:.2f} Hz. */\n\n'
        '#include "wx_clip.h"\n\n'
        f"const {ctype} wx_clip_samples[] = {{\n" + "\n".join(rows) + "\n};\n\n"
        f"const uint32_t wx_clip_count = {len(data)}U;\n")
    (out / "wx_clip.json").write_text(json.dumps(sidecar, indent=2) + "\n")
    (out / "wx_clip.txt").write_text("\n".join(expected_lines(sidecar)) + "\n")
    return sidecar


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--out", required=True, type=Path)
    p.add_argument("--bits", type=int, default=16, choices=(8, 16))
    a = p.parse_args(argv)
    side = build(a.out, a.bits)
    print(f"wrote {a.out}/wx_clip.c: {side['samples']} samples, {a.bits}-bit")
    return 0


if __name__ == "__main__":
    sys.exit(main())
